---
title: "進化社会学課題７"
author: "工科太郎"
date: "2024/2/08"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 課題の内容

A) ヘンリックのモデルにおいて、$\alpha=1$, $\beta=1$, $N=50$のもと、集団中の$z$値の最大値の時間変化を表すグラフを(線で)描画せよ。また、$z$値の集団平均のダイナミクスも、重ねて描画せよ。(最大値と平均値には異なる色を用いること。)ただし世代は$t=0\sim 100$とする。

B) $N=200$, $N=20$にして同様のシミュレーションを行った結果を、上のA)のグラフに重ねて描画せよ。

```{r assignment-7-AB}
# ここにコードを書いてください。
library(extraDistr)
henrich <- function(N,alpha,beta,gn) {
  z <- matrix(nrow=N,ncol=gn+1)
  z[,1] <- 0
  for(t in 1:gn) {
    z[,t+1] <- rgumbel(N,mu=max(z[,t]-alpha),sigma=beta)
  }
  return(z)
}
set.seed(123)
alpha <- 1
beta <- 1
N <- c(20,50,200)
gn <- 100

for(i in 1:length(N)){
  z <- henrich(N[i],alpha,beta,gn)
  plot(0:gn,apply(z,2,max),xlim=c(0,gn),ylim=c(0,300),
       xlab='generation',ylab='z',type='l',col='red')
  par(new=T)
  plot(0:gn,apply(z,2,mean),xlim=c(0,gn),ylim=c(0,300),
       xlab='generation',ylab='z',type='l',col='blue')
  par(new=T)
}
```

C) $\alpha=4$, $\beta=2$とする。$N$が50から1000まで50ずつ変化するとき、100世代後の集団における$z$の最大値がどのように変化するかを、横軸が$N$、縦軸が$z$の最大値のグラフを描いて確かめよ。

D) 上のグラフに、analytic関数を用いて、解析的予測値のグラフを重ねて描け。

```{r assignment-7-CD}
# ここにコードを書いてください。
analytic <- function(N,alpha,beta,gn) {
  egamma <- 0.57721566490153
  return(gn*(-alpha+beta*log(N)+beta*egamma))
}

N <- seq(50,1000,50)
alpha <- 4
beta <- 2
gn <- 100
res <- vector(length=length(N))
for(i in 1:length(N)) {
  z <- henrich(N[i],alpha,beta,gn)
  res[i] <- max(z[,gn+1])
}
plot(N,res,xlim=c(0,1000),ylim=c(0,1200),xlab='N',ylab='z_max in generation 100')
curve(analytic(x,alpha,beta,gn),xlim=c(0,1000),ylim=c(0,1200),xlab='',ylab='',add=T,col='red')

```